[workspace]
channels = ["conda-forge"]
name = "Lumitex"
platforms = ["linux-64"]
version = "0.1.0"

[pypi-options]
extra-index-urls = ["https://download.pytorch.org/whl/cu128"]

[tasks]
install-nvdiffrast = "pip install --no-build-isolation git+https://github.com/NVlabs/nvdiffrast.git"
install-custom-rasterizer = "pip install --no-build-isolation -e Renderer/custom_rasterizer"
compile-mesh-painter = "cd Renderer/DifferentiableRenderer && bash compile_mesh_painter.sh && cd ../.."
post-install = { depends-on = ["install-nvdiffrast", "install-custom-rasterizer", "compile-mesh-painter"] }

[dependencies]
python = "3.11.*"
pip = "*"
cuda-toolkit = "12.8.*"

[pypi-dependencies]
ninja = "*"
numpy = "<2"
pybind11 = "*"
transformers = "==4.56.2"
diffusers = "==0.35.1"
peft = "==0.17.1"
cupy-cuda12x = "*"
bpy = "*"
deepspeed = "*"
einops = "*"
accelerate = "==1.10.1"
nvidia-cublas-cu12 = "*"
bitsandbytes = "*"
wandb = "*"
kornia = "*"
open3d = "*"
trimesh = "*"
omegaconf = "*"
iopath = "*"
python-box = "*"
kiui = "*"
opencv-python = "*"
imageio = "*"
sentencepiece = "*"
gpytoolbox = "*"
pillow = "*"
timm = "*"
pymeshlab = "*"
rembg = "*"
scipy = "*"
onnxruntime = "*"
xatlas = "*"
coscmd = "*"
torch = { version = "==2.7.0", index = "https://download.pytorch.org/whl/cu128" }
torchvision = "==0.22.0"
torchaudio = "==2.7.0"
# icecream = ">=2.1.10, <3"
# prodigyopt = ">=1.1.2, <2"
# webdataset = ">=1.0.2, <2"
